# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2
    - uses: actions/checkout@v1
      
    - name: Get Repo README with repo name.
      env:
        OWNER: "opend-chiitah"
        REPO: "ScraperGUI"
      run: |
        curl -H "Authorization: Bearer ${{secrets.CUSTOM_TOKEN}}" \
        -H "Accept: application/vnd.github.raw" \
        -o "README-${REPO}.md" \
        https://api.github.com/repos/${OWNER}/${REPO}/readme
    # Runs a set of commands using the runners shell
    - name: 
      run: |
        git config --global user.name 'open-chiitah'
        git config --global user.email 'opend-chiitah@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Pushing README"
        git push
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
